# Generated by Django 5.1 on 2024-08-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                (
                    "property_type",
                    models.CharField(
                        choices=[("Apartment", "Apartment"), ("House", "House")],
                        max_length=50,
                    ),
                ),
                ("number_of_units", models.IntegerField()),
                ("rental_cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
