# Generated by Django 5.1 on 2024-08-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
